### ISSUE TITLE
Card title not displayed correctly in Safari

### ISSUE THREAD

**Issue by marcreichel** [marcreichel/apple-tv-card#34]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/7645035/169886133-61d4759e-a86c-433d-bab1-cdac3c999d5e.png">

Title is behind the shadow of the card.

**Comment by mohak34** [comment]
@marcreichel I would like to work on this issue and also would like some guidance on how to make it more visible

**Comment by marcreichel** [comment]
@mohak34 I'm not quiet sure yet how to fix this. This issue would be more or less just try and error to see what would fix it I guess.
